from typing import Any

class OldDatabase:
    FILE_NAME: Any = ...
    MONGO_URL: str = ...
    logger: Any = ...
    year: Any
    old_data: Any
    def __init__(self) -> None: ...
    def load(self, year: int, fp: str) -> None: ...
    def migrate(self) -> None: ...

test: Any
