from typing import Any

class OldDatabase:
    MONGO_URL: str = ...
    logger: Any = ...
    old_data: Any
    def __init__(self) -> None: ...
    def clean_data(self) -> None: ...
    year: Any = ...
    def load(self, year: int, fp: str) -> None: ...
    def migrate(self) -> None: ...
